---
# tasks file for dnsmasq
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present
  notify: enable dnsmasq
  tags:
    - dnsmasq

- name: Copy /etc/dnsmasq.conf
  template:
    src: "{{ dnsmasq_conf_src }}"
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  when: dnsmasq_conf_src is defined
  notify: restart dnsmasq
  tags:
    - dnsmasq

- name: Copy /etc/dnsmasq.d template files
  template:
    src: "{{ item }}"
    dest: /etc/dnsmasq.d
    mode: 0644
    owner: root
    group: root
    backup: true
  with_items: "{{ dnsmasq_conf_templates }}"
  when: dnsmasq_conf_templates is defined
  notify: restart dnsmasq
  tags:
    - dnsmasq
